export enum EPopupMode {
  ADD = "ADD",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  VIEW = "VIEW",
}

export enum OrderStatusEnum {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  PROCESSING = "PROCESSING",
  SHIPPING = "SHIPPING",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum PaymentMethodEnum {
  COD = "COD",
  BANKING = "BANKING",
}

export enum PaymentStatusEnum {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  UNPAID = "UNPAID",
}

export enum DiscountType {
  PERCENT = "PERCENT",
  FIXED = "FIXED",
}

export enum VerifyCodeEnum {
  RESEND_CODE = "RESEND_CODE",
  CREATE_ACCOUNT = "CREATE_ACCOUNT",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
}

export enum VoucherType {
  PERCENT = "PERCENT",
  FIXED = "FIXED",
}

export enum SocketEvent {
  ORDER_PAYMENT_EXPIRED = "ORDER_PAYMENT_EXPIRED",
  USER_CONNECTED = "USER_CONNECTED",
  USER_DISCONNECTED = "USER_DISCONNECTED",
  ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED",
  PAYMENT_SUCCESSFUL = "PAYMENT_SUCCESSFUL",
  JOIN_CONVERSATION = "JOIN_CONVERSATION",
  SEND_MESSAGE = "SEND_MESSAGE",
  NEW_MESSAGE = "NEW_MESSAGE",
  PRODUCT_PRICE_CHANGED = "PRODUCT_PRICE_CHANGED",
}

export enum EventType {
  ALL_SHOP = "ALL_SHOP",
  CATEGORY = "CATEGORY",
  SUBCATEGORY = "SUBCATEGORY",
}
